# Frozen-density, overdamped PMF pre-evolution using the same scale-dependent
# photon-baryon closure as the full radiation/Godunov path.

export radiation_terminal_velocity!, radiation_terminal_ct_induction!

@kernel function _radiation_terminal_velocity_hat_k!(hx, hy, hz,
        n::Int32, kfac::T, gamma_drag::T,
        rc::RadiationClosure{T}) where {T}
    p = @index(Global)
    h = (n >>> 1) + Int32(1)
    q = Int32(p - 1)
    ii = q % h
    q = q ÷ h
    jj = q % n
    kk = q ÷ n
    @inbounds begin
        kx = kfac * T(_radiation_mode_index(ii, n))
        ky = kfac * T(_radiation_mode_index(jj, n))
        kz = kfac * T(_radiation_mode_index(kk, n))
        k2 = kx*kx + ky*ky + kz*kz
        if k2 == zero(T) || !_radiation_mode_dealiased(
                ii, jj, kk, n, rc.nyquist_guard_fraction)
            hx[p] = zero(eltype(hx))
            hy[p] = zero(eltype(hy))
            hz[p] = zero(eltype(hz))
        else
            x = hx[p]
            y = hy[p]
            z = hz[p]
            ik2 = inv(k2)
            kdot = kx*x + ky*y + kz*z
            stream, inertia, gamma_t, gamma_l, _ =
                _radiation_mode_coefficients(k2, gamma_drag, rc)
            # In tight coupling radiation pressure balances the longitudinal
            # Lorentz force when density is frozen. In free streaming that
            # pressure support vanishes, so local drag responds to the full
            # force. The closure's compact bridge supplies the handoff.
            response_t = inertia / max(gamma_t, eps(T))
            response_l = stream * inertia / max(gamma_l, eps(T))
            lx = kx*kdot*ik2
            ly = ky*kdot*ik2
            lz = kz*kdot*ik2
            hx[p] = response_t * (x - lx) + response_l * lx
            hy[p] = response_t * (y - ly) + response_l * ly
            hz[p] = response_t * (z - lz) + response_l * lz
        end
    end
end

@kernel function _radiation_terminal_speed_k!(speed,
        @Const(vx), @Const(vy), @Const(vz))
    c = @index(Global)
    @inbounds speed[c] = sqrt(vx[c]*vx[c] + vy[c]*vy[c] + vz[c]*vz[c])
end

@kernel function _radiation_terminal_divergence2_k!(work,
        @Const(vx), @Const(vy), @Const(vz), n::Int, inv2dx)
    c = @index(Global)
    @inbounds begin
        i = (c - 1) % n + 1
        j = ((c - 1) ÷ n) % n + 1
        k = (c - 1) ÷ (n*n) + 1
        d = (vx[_tct_lin3(i + 1, j, k, n)] - vx[_tct_lin3(i - 1, j, k, n)] +
             vy[_tct_lin3(i, j + 1, k, n)] - vy[_tct_lin3(i, j - 1, k, n)] +
             vz[_tct_lin3(i, j, k + 1, n)] - vz[_tct_lin3(i, j, k - 1, n)]) * inv2dx
        work[c] = d*d
    end
end

function _radiation_terminal_closure(::Type{T}, closure::RadiationClosure) where {T}
    RadiationClosure{T}(T(closure.inertia_ratio), T(closure.mean_free_path),
        T(closure.photon_speed), T(closure.gas_sound_speed), T(closure.bridge_q2),
        T(closure.longitudinal_viscosity), T(closure.nyquist_guard_fraction),
        closure.response_model)
end

"""
    radiation_terminal_velocity!(ws, s; state=s.U, gamma_drag, closure)

Compute the frozen-density overdamped velocity generated by the magnetic
Maxwell stress. The transverse response is scale dependent. The longitudinal
response is suppressed by radiation pressure in tight coupling and restored as
the closure approaches free streaming. The same `RadiationClosure` is used by
`step_radiation_godunov!`. The three returned arrays alias `ws.correction` and
remain on the device.
"""
function radiation_terminal_velocity!(ws::RadiationWorkspace,
        s::MHDState{T}; state=s.U, gamma_drag::Real,
        closure::RadiationClosure) where {T}
    all_periodic(s) || error("spectral terminal induction requires periodic boundaries")
    gamma_drag >= 0 || error("radiation gamma_drag must be non-negative")
    rc = _radiation_terminal_closure(T, closure)
    n = s.dims[1]
    kfac = T(2pi) / (T(n) * s.dx)
    fundamental = radiation_mode_coefficients(kfac, T(gamma_drag), rc)
    fundamental.gamma_transverse > eps(T) ||
        error("radiation terminal response is undefined without transverse damping")

    out = ws.correction
    fx, fy, fz = out
    inv2dx = inv(T(2) * s.dx)
    _tct_magnetic_force_k!(s.be)(fx, fy, fz, state[6], state[7], state[8],
                                 n, inv2dx; ndrange=ncells(s))
    _radiation_force_to_accel_k!(s.be)(fx, fy, fz, state[1], s.smallr;
                                       ndrange=ncells(s))
    KA.synchronize(s.be)
    _radiation_forward_triplet!(ws, out)
    _radiation_terminal_velocity_hat_k!(s.be)(ws.velocity_hat...,
        Int32(n), kfac, T(gamma_drag), rc;
        ndrange=length(ws.velocity_hat[1]))
    KA.synchronize(s.be)
    _radiation_inverse_triplet!(out, ws)
    return out
end

@inline function _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i, j, k, n)
    c = _tct_lin3(i, j, k, n)
    x = vx[c]
    y = vy[c]
    z = vz[c]
    bx = Bx[c]
    by = By[c]
    bz = Bz[c]
    return y*bz - z*by, z*bx - x*bz, x*by - y*bx
end

@inline function _rtct_rhs_at(vx, vy, vz, Bx, By, Bz,
                              i, j, k, n, inv2dx, invdx2, eta,
                              dissipation_order::Int)
    eyp = _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i, j + 1, k, n)
    eym = _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i, j - 1, k, n)
    ezp = _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i, j, k + 1, n)
    ezm = _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i, j, k - 1, n)
    exp = _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i + 1, j, k, n)
    exm = _rtct_emf_at(vx, vy, vz, Bx, By, Bz, i - 1, j, k, n)
    dx = ((eyp[3] - eym[3]) - (ezp[2] - ezm[2])) * inv2dx
    dy = ((ezp[1] - ezm[1]) - (exp[3] - exm[3])) * inv2dx
    dz = ((exp[2] - exm[2]) - (eyp[1] - eym[1])) * inv2dx
    if dissipation_order == 4
        return dx - eta * _tct_bilap_at(Bx, i, j, k, n, invdx2),
               dy - eta * _tct_bilap_at(By, i, j, k, n, invdx2),
               dz - eta * _tct_bilap_at(Bz, i, j, k, n, invdx2)
    end
    return dx + eta * _tct_lap_at(Bx, i, j, k, n, invdx2),
           dy + eta * _tct_lap_at(By, i, j, k, n, invdx2),
           dz + eta * _tct_lap_at(Bz, i, j, k, n, invdx2)
end

@kernel function _rtct_predict_k!(pBx, pBy, pBz,
        @Const(vx), @Const(vy), @Const(vz),
        @Const(Bx), @Const(By), @Const(Bz),
        n::Int, dt, inv2dx, invdx2, eta, dissipation_order::Int)
    c = @index(Global)
    @inbounds begin
        i = (c - 1) % n + 1
        j = ((c - 1) ÷ n) % n + 1
        k = (c - 1) ÷ (n*n) + 1
        x, y, z = _rtct_rhs_at(vx, vy, vz, Bx, By, Bz, i, j, k, n,
                               inv2dx, invdx2, eta, dissipation_order)
        pBx[c] = Bx[c] + dt*x
        pBy[c] = By[c] + dt*y
        pBz[c] = Bz[c] + dt*z
    end
end

@kernel function _rtct_correct_k!(Bx, By, Bz, E,
        @Const(vx), @Const(vy), @Const(vz),
        @Const(pBx), @Const(pBy), @Const(pBz),
        rx, ry, rz, n::Int, dt, inv2dx, invdx2, eta,
        dissipation_order::Int, smallE, compensated::Val{COMP}) where {COMP}
    c = @index(Global)
    @inbounds begin
        T = eltype(E)
        i = (c - 1) % n + 1
        j = ((c - 1) ÷ n) % n + 1
        k = (c - 1) ÷ (n*n) + 1
        x, y, z = _rtct_rhs_at(vx, vy, vz, pBx, pBy, pBz, i, j, k, n,
                               inv2dx, invdx2, eta, dissipation_order)
        ox = Bx[c]
        oy = By[c]
        oz = Bz[c]
        dix = T(0.5) * ((pBx[c] - ox) + dt*x)
        diy = T(0.5) * ((pBy[c] - oy) + dt*y)
        diz = T(0.5) * ((pBz[c] - oz) + dt*z)
        if COMP
            dx = dix + rx[c]
            dy = diy + ry[c]
            dz = diz + rz[c]
            nx = ox + dx
            ny = oy + dy
            nz = oz + dz
            rx[c] = (ox - nx) + dx
            ry[c] = (oy - ny) + dy
            rz[c] = (oz - nz) + dz
        else
            nx = ox + dix
            ny = oy + diy
            nz = oz + diz
        end
        eb0 = T(0.5) * (ox*ox + oy*oy + oz*oz)
        eb1 = T(0.5) * (nx*nx + ny*ny + nz*nz)
        Bx[c] = nx
        By[c] = ny
        Bz[c] = nz
        E[c] = max(E[c] + eb1 - eb0, smallE)
    end
end

"""
    radiation_terminal_ct_induction!(s, ws, dt; gamma_drag, closure,
                                     cfl=0.4, dissipation=0.05,
                                     dissipation_order=4, max_subcycles=256,
                                     compensation=nothing, diagnostics=false)

Advance only `B` through the scale-dependent overdamped photon-baryon response.
Density, momentum, and thermal energy are invariant. Lorentz force and terminal
velocity are recomputed from the predictor field at every SSPRK2 stage.
When `compensation=(rx,ry,rz)` is supplied, those persistent Float32 residuals
retain sub-ulp magnetic increments across calls. The caller must zero them once
before the first step and keep them untouched between steps. With
`diagnostics=true`, the returned tuple also measures the RMS compressive rate
and the fundamental drag-to-induction rate ratio entirely on the device.
"""
function radiation_terminal_ct_induction!(s::MHDState{T}, ws::RadiationWorkspace,
        dt::Real; gamma_drag::Real, closure::RadiationClosure,
        cfl::Real=0.4, dissipation::Real=0.05,
        dissipation_order::Int=4, max_subcycles::Int=256,
        compensation=nothing, diagnostics::Bool=false) where {T}
    dt > 0 || error("radiation terminal CT dt must be positive")
    0 < cfl <= 1 || error("radiation terminal CT cfl must be in (0,1]")
    0 <= dissipation <= 1 || error("radiation terminal CT dissipation must be in [0,1]")
    dissipation_order in (2, 4) ||
        error("radiation terminal CT dissipation_order must be 2 or 4")
    n = s.dims[1]
    all(==(n), s.dims) || error("radiation terminal CT requires a cubic grid")

    velocity = radiation_terminal_velocity!(ws, s;
        gamma_drag=gamma_drag, closure=closure)
    _radiation_terminal_speed_k!(s.be)(s.scratch[1], velocity...;
                                       ndrange=ncells(s))
    KA.synchronize(s.be)
    vmax = Float64(maximum(s.scratch[1]))
    divergence_rms = NaN
    if diagnostics
        _radiation_terminal_divergence2_k!(s.be)(s.scratch[1], velocity...,
            n, inv(T(2) * s.dx); ndrange=ncells(s))
        KA.synchronize(s.be)
        divergence_rms = sqrt(max(Float64(sum(s.scratch[1])) / ncells(s), 0.0))
    end
    nsub = max(1, ceil(Int, Float64(dt) * vmax /
                           max(Float64(cfl) * Float64(s.dx), eps(Float64))))
    nsub <= max_subcycles ||
        error("radiation terminal CT needs $nsub subcycles (limit $max_subcycles)")
    dts = T(dt / nsub)
    inv2dx = inv(T(2) * s.dx)
    invdx2 = inv(s.dx * s.dx)
    eta = dissipation_order == 4 ?
          T(dissipation / 12) * T(vmax) * s.dx^3 :
          T(dissipation) * T(vmax) * s.dx
    residual = compensation === nothing ?
               (s.scratch[2], s.scratch[3], s.scratch[4]) : compensation
    compensated = Val(compensation !== nothing)

    for subcycle in 1:nsub
        if subcycle > 1
            velocity = radiation_terminal_velocity!(ws, s;
                gamma_drag=gamma_drag, closure=closure)
        end
        _rtct_predict_k!(s.be)(s.scratch[6], s.scratch[7], s.scratch[8],
            velocity..., s.U[6], s.U[7], s.U[8], n, dts, inv2dx, invdx2,
            eta, dissipation_order; ndrange=ncells(s))
        predictor = (s.U[1], s.U[2], s.U[3], s.U[4], s.U[5],
                     s.scratch[6], s.scratch[7], s.scratch[8], s.U[9])
        velocity = radiation_terminal_velocity!(ws, s; state=predictor,
            gamma_drag=gamma_drag, closure=closure)
        _rtct_correct_k!(s.be)(s.U[6], s.U[7], s.U[8], s.U[5],
            velocity..., s.scratch[6], s.scratch[7], s.scratch[8],
            residual..., n, dts, inv2dx, invdx2, eta, dissipation_order,
            T(1e-30), compensated;
            ndrange=ncells(s))
    end
    KA.synchronize(s.be)
    rc = _radiation_terminal_closure(T, closure)
    kfund = T(2pi) / (T(n) * s.dx)
    mode = radiation_mode_coefficients(kfund, T(gamma_drag), rc)
    active_gamma_l = mode.streaming_weight > sqrt(eps(T)) ?
                     mode.gamma_longitudinal : T(Inf)
    gamma_min = min(mode.gamma_transverse, active_gamma_l)
    induction_rate = vmax / Float64(s.dx)
    relaxation_ratio = Float64(gamma_min) /
        max(induction_rate, eps(Float64))
    return (nsubcycles=nsub, vmax=vmax, eta=Float64(eta),
            divergence_rms=divergence_rms,
            density_change_bound=diagnostics ? Float64(dt) * divergence_rms : NaN,
            relaxation_ratio=relaxation_ratio,
            streaming_weight=Float64(mode.streaming_weight))
end
